#!/usr/bin/env python3
from __future__ import annotations

import argparse
import fcntl
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import List

from sidecar_config import dump_env_file, load_config


def parse_uid_list(raw: str) -> List[str]:
    seen = set()
    ordered: List[str] = []
    for item in raw.split(","):
        uid = item.strip()
        if not uid:
            continue
        if not uid.isdigit():
            raise SystemExit(f"invalid uid: {uid}")
        if uid == "0":
            raise SystemExit("refusing to transparently proxy uid 0")
        if uid in seen:
            continue
        seen.add(uid)
        ordered.append(uid)
    return ordered


def current_uid_list(config: dict) -> List[str]:
    raw = config.get("MIHOMO_TRANSPARENT_UIDS", "").strip()
    if raw:
        return parse_uid_list(raw)
    legacy_uid = config.get("MIHOMO_TARGET_UID", "").strip()
    if legacy_uid:
        return parse_uid_list(legacy_uid)
    return []


def apply_uid_list(config: dict, uids: List[str]) -> None:
    config["MIHOMO_TRANSPARENT_UIDS"] = ",".join(uids)
    config["MIHOMO_TRANSPARENT_ENABLED"] = "1" if uids else "0"
    config["MIHOMO_TARGET_UID"] = uids[0] if uids else ""


def service_is_active(service_name: str) -> bool:
    if not shutil.which("systemctl"):
        return False
    proc = subprocess.run(
        ["systemctl", "is-active", "--quiet", service_name],
        check=False,
        capture_output=True,
        text=True,
    )
    return proc.returncode == 0


def run_script(path: str) -> None:
    proc = subprocess.run([path], check=False, capture_output=True, text=True)
    if proc.returncode != 0:
        message = (proc.stderr or proc.stdout).strip() or f"command failed: {path}"
        raise SystemExit(message)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="管理 mihomo-sidecar-linux 的透明代理 UID 列表")
    parser.add_argument("--config", help="sidecar.env 路径")
    parser.add_argument("--action", choices=["add", "remove", "clear", "status"], required=True)
    parser.add_argument("--uid", action="append", default=[], help="要添加或移除的 UID，可重复")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    explicit_config = args.config or os.environ.get("MIHOMO_SIDECAR_CONFIG")
    initial_config = load_config(Path(__file__).resolve(), explicit_config=explicit_config)
    runtime_env = Path(initial_config["MIHOMO_RUNTIME_ENV"]).expanduser()
    lock_path = runtime_env.with_suffix(runtime_env.suffix + ".lock")
    lock_path.parent.mkdir(parents=True, exist_ok=True)

    requested_uids = []
    for raw_uid in args.uid:
        requested_uids.extend(parse_uid_list(raw_uid))

    with lock_path.open("a+", encoding="utf-8") as lock_file:
        fcntl.flock(lock_file.fileno(), fcntl.LOCK_EX)
        config = load_config(Path(__file__).resolve(), explicit_config=explicit_config)
        current = current_uid_list(config)

        if args.action == "status":
            print(",".join(current))
            return
        if args.action == "add":
            for uid in requested_uids:
                if uid not in current:
                    current.append(uid)
        elif args.action == "remove":
            current = [uid for uid in current if uid not in set(requested_uids)]
        elif args.action == "clear":
            current = []

        apply_uid_list(config, current)
        dump_env_file(config, runtime_env, header="Generated by script/transparent_mode.py")

        if service_is_active(config["MIHOMO_SERVICE_NAME"]):
            run_script(config["MIHOMO_CLEANUP_SCRIPT"])
            run_script(config["MIHOMO_SETUP_SCRIPT"])

        print(",".join(current))


if __name__ == "__main__":
    main()
