#!/usr/bin/env python3
from __future__ import annotations

import argparse
import fcntl
import os
from pathlib import Path

from sidecar_config import dump_env_file, load_config


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="更新 mihomo-sidecar-linux 的 runtime.env")
    parser.add_argument("--config", help="sidecar.env 路径")
    parser.add_argument("--output", help="runtime.env 路径，默认使用当前配置里的 MIHOMO_RUNTIME_ENV")
    parser.add_argument("--set", action="append", default=[], metavar="KEY=VALUE", help="写入或覆盖一个变量")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    config = load_config(Path(__file__).resolve(), explicit_config=args.config or os.environ.get("MIHOMO_SIDECAR_CONFIG"))
    output = Path(args.output or config["MIHOMO_RUNTIME_ENV"]).expanduser()
    lock_path = output.with_suffix(output.suffix + ".lock")
    lock_path.parent.mkdir(parents=True, exist_ok=True)

    with lock_path.open("a+", encoding="utf-8") as lock_file:
        fcntl.flock(lock_file.fileno(), fcntl.LOCK_EX)
        config = load_config(Path(__file__).resolve(), explicit_config=args.config or os.environ.get("MIHOMO_SIDECAR_CONFIG"))
        for item in args.set:
            if "=" not in item:
                raise SystemExit(f"无效参数，必须是 KEY=VALUE: {item}")
            key, value = item.split("=", 1)
            config[key] = value
        dump_env_file(config, output, header="Generated by script/update_runtime_env.py")


if __name__ == "__main__":
    main()
